[package]
name = "macros"
version = "0.1.0"
authors = ["Matteo Monti <matteo.monti@epfl.ch>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.30"
quote = "0.6.12"
syn = "0.15.34"
